package com.example.loyalty.application.service;

import com.example.loyalty.application.dto.LoyaltyDtos.*;
import com.example.loyalty.application.port.*;
import com.example.loyalty.domain.model.*;
import com.example.loyalty.domain.service.*;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

@Service
public class LoyaltyFacade {
    private final CustomerQueryService customerQueryService; private final LoyaltyAccountRepository accounts; private final RewardTransactionRepository transactions; private final OfferRepository offers; private final ClaimedOfferRepository claimedOffers; private final OfferStrategyFactory strategies; private final PurchaseInsightService purchaseInsights; private final JdbcTemplate jdbcTemplate;
    public LoyaltyFacade(CustomerQueryService customerQueryService, LoyaltyAccountRepository accounts, RewardTransactionRepository transactions, OfferRepository offers, ClaimedOfferRepository claimedOffers, OfferStrategyFactory strategies, PurchaseInsightService purchaseInsights, JdbcTemplate jdbcTemplate) { this.customerQueryService = customerQueryService; this.accounts = accounts; this.transactions = transactions; this.offers = offers; this.claimedOffers = claimedOffers; this.strategies = strategies; this.purchaseInsights = purchaseInsights; this.jdbcTemplate = jdbcTemplate; }
    @Transactional(readOnly = true) public BalanceDto balance(String email) { Customer customer = customerQueryService.requireByEmail(email); LoyaltyAccount account = accounts.findByCustomer(customer).orElseThrow(() -> new NotFoundException("Loyalty account not found")); return new BalanceDto(customer.getId(), account.getPointsBalance(), customer.getSegment()); }
    @Transactional(readOnly = true) public List<OfferDto> personalizedOffers(String email) { Customer customer = customerQueryService.requireByEmail(email); var profile = purchaseInsights.profile(customer); return offers.findByStatus(OfferStatus.ACTIVE).stream().sorted((left, right) -> Integer.compare(offerScore(customer, profile, right), offerScore(customer, profile, left))).map(offer -> toOfferDto(customer, profile, offer)).toList(); }
    @Transactional public OfferDto claim(String email, Long offerId) { Customer customer = customerQueryService.requireByEmail(email); Offer offer = offers.findById(offerId).orElseThrow(() -> new NotFoundException("Offer not found")); if (claimedOffers.existsByCustomerAndOffer(customer, offer)) throw new BusinessRuleViolationException("Offer already claimed"); claimedOffers.save(new ClaimedOffer(customer, offer)); var profile = purchaseInsights.profile(customer); return toOfferDto(customer, profile, offer); }
    @Transactional public RedemptionDto redeem(String email, RedemptionRequest request) { Customer customer = customerQueryService.requireByEmail(email); LoyaltyAccount account = accounts.findByCustomer(customer).orElseThrow(() -> new NotFoundException("Loyalty account not found")); if (account.getPointsBalance() < request.points()) throw new BusinessRuleViolationException("Not enough points"); var profile = purchaseInsights.profile(customer); String category = request.targetCategory() == null || request.targetCategory().isBlank() ? purchaseInsights.recommendedCertificateCategory(profile) : request.targetCategory(); BigDecimal discount = BigDecimal.valueOf(request.points()).divide(BigDecimal.TEN); String code = "LP-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase(); account.redeem(request.points()); transactions.save(new RewardTransaction(account, RewardTransactionType.REDEEM, -request.points(), "Redeemed for " + request.rewardName() + " (" + category + ")")); jdbcTemplate.update("insert into redemption_orders(customer_id, account_id, points_spent, discount_amount, reward_name, confirmation_code, target_category) values (?, ?, ?, ?, ?, ?, ?)", customer.getId(), account.getId(), request.points(), discount, request.rewardName(), code, category); return new RedemptionDto(request.points(), discount, account.getPointsBalance(), code, request.rewardName(), category, purchaseInsights.certificateReason(profile, category)); }
    @Transactional(readOnly = true) public List<CertificateDto> certificates(String email) { Customer customer = customerQueryService.requireByEmail(email); return jdbcTemplate.query("""
        select id, points_spent, discount_amount, reward_name, confirmation_code, status, created_at, expires_at, used_at, purchase_id, target_category
        from redemption_orders
        where customer_id = ?
        order by created_at desc
        """, (rs, rowNum) -> new CertificateDto(rs.getLong("id"), rs.getInt("points_spent"), rs.getBigDecimal("discount_amount"), rs.getString("reward_name"), rs.getString("confirmation_code"), rs.getString("target_category"), rs.getString("status"), rs.getObject("created_at", java.time.OffsetDateTime.class), rs.getObject("expires_at", java.time.OffsetDateTime.class), rs.getObject("used_at", java.time.OffsetDateTime.class), (Long) rs.getObject("purchase_id")), customer.getId()); }
    @Transactional public CustomerSegment recalculateSegment(String email) { Customer customer = customerQueryService.requireByEmail(email); java.math.BigDecimal total = jdbcTemplate.queryForObject("select coalesce(sum(total_amount),0) from purchases where customer_id = ?", java.math.BigDecimal.class, customer.getId()); int spent = total == null ? 0 : total.intValue(); customer.setSegment(spent > 700 ? CustomerSegment.PREMIUM : spent > 150 ? CustomerSegment.REGULAR : CustomerSegment.NEWCOMER); return customer.getSegment(); }
    @Transactional(readOnly = true) public Page<RewardTransactionDto> transactions(String email, Pageable pageable) { Customer customer = customerQueryService.requireByEmail(email); LoyaltyAccount account = accounts.findByCustomer(customer).orElseThrow(() -> new NotFoundException("Loyalty account not found")); return transactions.findByAccount(account, pageable).map(tx -> new RewardTransactionDto(tx.getId(), tx.getType(), tx.getPoints(), tx.getReason(), tx.getCreatedAt())); }
    @Transactional(readOnly = true) public PurchaseProfileDto purchaseProfile(String email) { Customer customer = customerQueryService.requireByEmail(email); var profile = purchaseInsights.profile(customer); return new PurchaseProfileDto(profile.categories().stream().map(category -> new CategoryInsightDto(category.category(), category.purchaseCount(), category.spent(), purchaseInsights.sharePercent(profile, category), category.lastPurchaseAt() == null ? null : category.lastPurchaseAt().toString(), purchaseInsights.categoryAverageCheck(category))).toList(), profile.purchaseCount(), profile.totalSpent(), profile.lastPurchaseAt() == null ? null : profile.lastPurchaseAt().toString(), purchaseInsights.averageCheck(profile), purchaseInsights.frequencyLabel(profile), purchaseInsights.buyerRating(profile), purchaseInsights.buyerRatingLabel(profile)); }
    @Transactional(readOnly = true) public LoyaltyProgramDto program() { List<RewardRuleDto> rewardRules = jdbcTemplate.query("select category, cashback_percent, description from reward_rules where active = true order by cashback_percent desc", (rs, rowNum) -> new RewardRuleDto(rs.getString("category"), rs.getBigDecimal("cashback_percent"), rs.getString("description"))); List<SegmentRuleDto> segmentRules = jdbcTemplate.query("select segment, min_total_spend, multiplier, description from customer_segment_thresholds order by min_total_spend", (rs, rowNum) -> new SegmentRuleDto(CustomerSegment.valueOf(rs.getString("segment")), rs.getBigDecimal("min_total_spend"), rs.getBigDecimal("multiplier"), rs.getString("description"))); return new LoyaltyProgramDto(rewardRules, segmentRules, "10 points = 1 discount currency unit. Minimum redemption is 50 points."); }
    private OfferDto toOfferDto(Customer customer, PurchaseInsightService.PurchaseProfile profile, Offer offer) { String lifecycle = offerLifecycle(customer.getId(), offer.getId()); BigDecimal baseline = purchaseInsights.averageCheck(profile); BigDecimal target = baseline.multiply(BigDecimal.valueOf(1.2)).setScale(2, java.math.RoundingMode.HALF_UP); BigDecimal current = purchaseInsights.categoryAverageCheck(profile.categories().stream().filter(category -> category.category().equals(offer.getTargetCategory())).findFirst().orElse(new PurchaseInsightService.CategoryStat(offer.getTargetCategory(), 0, BigDecimal.ZERO, null))); int progress = target.compareTo(BigDecimal.ZERO) == 0 ? 0 : current.multiply(BigDecimal.valueOf(100)).divide(target, 0, java.math.RoundingMode.HALF_UP).min(BigDecimal.valueOf(100)).intValue(); int requiredRating = offer.getBonusPoints() >= 200 ? 70 : offer.getBonusPoints() >= 120 ? 45 : 20; String nextStep = switch (lifecycle) { case "CLAIMED" -> "Задание активно: купите " + offer.getTargetCategory() + " на чек от " + target.intValue() + " ₽. Прогресс сейчас " + progress + "%."; case "USED" -> "Задание выполнено, бонус уже начислен. Следующее задание появится по новой истории покупок."; default -> purchaseInsights.buyerRating(profile) >= requiredRating ? "Можно активировать. Цель: увеличить средний чек до " + target.intValue() + " ₽ в категории " + offer.getTargetCategory() + "." : "Пока заблокировано: нужен рейтинг покупателя " + requiredRating + "+. Делайте покупки и повышайте активность."; }; return new OfferDto(offer.getId(), offer.getTitle(), offer.getDescription(), offer.getTargetCategory(), offer.getBonusPoints(), offer.getValidUntil(), offerScore(customer, profile, offer), purchaseInsights.explanation(profile, offer.getTargetCategory()), lifecycle, nextStep, "AVERAGE_CHECK_GROWTH", baseline, target, current, progress, requiredRating, "Увеличить средний чек и развить категорию " + offer.getTargetCategory()); }
    private int offerScore(Customer customer, PurchaseInsightService.PurchaseProfile profile, Offer offer) { return strategies.combinedScore(customer, offer) + purchaseInsights.historyScore(profile, offer.getTargetCategory()); }
    private String offerLifecycle(Long customerId, Long offerId) { return jdbcTemplate.query("select status from claimed_offers where customer_id = ? and offer_id = ?", rs -> rs.next() ? rs.getString("status") : "AVAILABLE", customerId, offerId); }
}
